### ISSUE TITLE
500 error on /dashboard/ after updating to a build using Python 3.14

### ISSUE THREAD

**Issue by regalen** [babybuddy/babybuddy#1103]
### Describe the bug

After updating my Docker image this morning, logging in redirects me to `/dashboard/` and I get a 500 Server Error. Every other page I've tried works fine. Turning on debug gives the traceback below, which points at django-imagekit and the child thumbnail template.

I noticed the new build moved to Python 3.14 (the previous one was on 3.13), and going back to the older image tag fixes it, so I suspect it's a Python version compatibility problem rather than anything in Baby Buddy itself. Posting here in case it's the right place, happy to move it if not.

### To Reproduce

1. Run Baby Buddy on a build using Python 3.14.
2. Have a child with a profile picture uploaded.
3. Log in and go to `/dashboard/`.
4. 500 Server Error.

It seems to depend on the child having a picture. I only worked that out from the traceback pointing at `child_thumbnail.html`, so I haven't tested removing the picture to confirm.

### Traceback

```
Request Method: GET
Request URL: http://<host>:8000/dashboard/

Django Version: 5.2.14
Python Version: 3.14.5
Exception Type: TypeError
Exception Value: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'
Exception Location: /lsiopy/lib/python3.14/site-packages/imagekit/hashers.py, line 22, in save_dict
Raised during: dashboard.views.Dashboard

Error during template rendering
In template /app/www/public/core/templates/core/child_thumbnail.html, error at line 3

  1 {% load imagekit static %}
  2 {% if child.picture %}
  3     {% thumbnail '40x40' child.picture as thumb %}
  4         <img src="{{ thumb.url }}" class="img-fluid rounded-circle" />
  5     {% else %}

  File "/lsiopy/lib/python3.14/site-packages/imagekit/hashers.py", line 22, in save_dict
    self._batch_setitems(sorted(obj.items()))

when serializing pilkit.processors.resize.Thumbnail state
when serializing pilkit.processors.resize.Thumbnail object
when serializing list item 0
when serializing list item 1
```

### Environment

- Baby Buddy version: v2.9.2
- Deployment: LinuxServer.io Docker image, tag `v2.9.2-ls243` (build date 2026-08-02)
- Python: 3.14.5
- Django: 5.2.14
- django-imagekit
- Database: SQLite (default)
- Host OS: Fedora Server, Docker

### Workaround

Pinning back to the previous image tag, `v2.9.2-ls242`, fixed it for me. That one is on Python 3.13. Both tags are the same Baby Buddy version, so nothing else changed and my data was unaffected.

**Comment by poldim** [comment]
temp fix for me:
`docker exec -it srv_babybuddy /bin/bash -c "sed -i 's/self._batch_setitems(sorted(obj.items()))/self._batch_setitems(sorted(obj.items()), obj)/g' /lsiopy/lib/python3.14/site-packages/imagekit/hashers.py"`

**Comment by freakadings** [comment]
Same here.
For Unraid-users: On Unraid I had to set the image back to "lscr.io/linuxserver/babybuddy:v2.9.2-ls242".

**Comment by jwalker343** [comment]
I also ran into this issue, I removed my child's photo using the admin tool (`/admin/core/child/`) which immediately allowed me to navigate normally and enter feedings, etc... so I can confirm that is also a temporary stop-gap/work-around.

<img width="618" height="652" alt="Image" src="https://github.com/user-attachments/assets/aa76ee77-1dd0-4dd1-8239-53bafde4927b" />
